### ISSUE TITLE
get all initial code & specs in tf_cockpit repo

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/tf_cockpit#1]
- [ ] link to examples how cockpit will be created
- [x] link to mindmap
- [x] identify who is owner
- [ ] any other specs
- [x] create issues for what needs to be done for the tf_cockpit, assign where possible

**Comment by andhartl** [comment]
will start to work on it today afternoon

**Comment by zaibon** [comment]
I had created a project to start organizing task about the tf_cockpit already: https://github.com/orgs/threefoldtech/projects/41
if we are going to use this repo then I need to move the project into this organization instead. (although I'm not sure why we would put in in this organization in the first place, see #2)

Otherwise I already opened a group with people that needs to be working on this. I'm planning to do a first bootstrap meeting tomorrow (Monday 18 august) so we can all be in sync with what needs to be done.

Once this meeting is done I will creates al the tasks, move the already existing code and specs in this repository
