### ISSUE TITLE
Track Atomic Swap fulfilment time and publish with Farmer transaction

### ISSUE THREAD

**Issue by andhartl** [threefoldtech/tf_cockpit#8]
Track fulfilment time instead of giving the farmer a rating. this solution is more decentralised and shows facts which can be taken into consideration by a buyer

**Comment by zaibon** [comment]
Let me elaborate a bit more about this problem.

The idea is that from the cockpit, farmers can post sell offers, and then anyone can create a transaction using atomic swap to exchange TFT against another coin/token.

This give us 2 challenges:
- We want to give a "rating" to the sellers. Whatever this rating really means is still to be clearly defined.
- We need to find a way to be notified when a transaction that has been initiate because of the sell offer on the cockpit is actually fulfilled. 

The second is the hardest to solve. We need this info for 2 reasons:
- we want to use this information to somehow compute a rating...
- we need to know when an offer is not available anymore so we can remove it from the dashboard.
